typography_spectrum: 0.225827450864017
color:
  brandColors: []
  brandStrength: 0.6918297314550728
  lightness: 0.087914670817554
  saturation: 0.14862392959184945
  rhythmicContrast: 0.002073219744488597
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7679007828701288
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Richard S Davies
  email: me@richardsdavies.com
name: Richard S Davies
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Creative Director and Lover of Wandering
purpose: []
